version: '3.8'
services:

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: dammchik
      POSTGRES_PASSWORD: 123
    ports:
      - "15432:5432"
    restart: unless-stopped

volumes:
  db-data:
  pgadmin-data: