version: '3.8'
services:

  service-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barbershopdb
    ports:
      - "15432:5432"
    
    restart: unless-stopped
